### ISSUE TITLE
Add support for supplementary characters

### ISSUE THREAD

**Issue by amtlib-dot-dll** [EdiWang/UWP-CharacterMap#5] opened 2016-07-28 02:24 UTC
This app is great, but I cannot find any character higher than U+FFFF, for example, 🔞(U+1F51E). Looking forward to the support of emoji's. Thank you very much:smile:

**Comment by EdiWang** [comment] 2017-01-21 11:47
This is not the scope of this App now. But thanks anyway! It's a great idea, I may plan it in future release.

**Comment by EdiWang** [comment] 2017-09-27 07:50
The issue is fixed in today's release. Closing it now.

**Closed by EdiWang** 2017-09-27 07:50 UTC
